/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import javax.swing.ImageIcon;
import javax.swing.JToggleButton;

/**
 *
 * @author tians
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private int[][] matriz={{0,0,0},{0,0,0},{0,0,0}};
private boolean turno=true;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btn00 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        btn20 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn01 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn21 = new javax.swing.JToggleButton();
        btn02 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(90, 90));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 330, 400, 10);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 110, 10, 330);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 110, 10, 330);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 400, 10);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("*** Juego Tres En Raya ***\n~~~~~ Pulse un boton ~~~~~");
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(253, 153, 153)));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 490, 660, 240);

        btnReset.setBackground(new java.awt.Color(102, 102, 0));
        btnReset.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnReset.setText("REINICIAR");
        getContentPane().add(btnReset);
        btnReset.setBounds(450, 170, 240, 90);

        btn00.setBackground(new java.awt.Color(0, 162, 232));
        btn00.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        getContentPane().add(btn00);
        btn00.setBounds(40, 110, 110, 90);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Tres en Raya");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 10, 330, 60);

        btn20.setBackground(new java.awt.Color(0, 162, 232));
        btn20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20);
        btn20.setBounds(40, 350, 110, 90);

        btn10.setBackground(new java.awt.Color(0, 162, 232));
        btn10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(40, 230, 110, 90);

        btn01.setBackground(new java.awt.Color(0, 162, 232));
        btn01.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        getContentPane().add(btn01);
        btn01.setBounds(180, 110, 110, 90);

        btn11.setBackground(new java.awt.Color(0, 162, 232));
        btn11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11);
        btn11.setBounds(180, 230, 110, 90);

        btn21.setBackground(new java.awt.Color(0, 162, 232));
        btn21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21);
        btn21.setBounds(180, 350, 110, 90);

        btn02.setBackground(new java.awt.Color(0, 162, 232));
        btn02.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        getContentPane().add(btn02);
        btn02.setBounds(320, 110, 110, 90);

        btn12.setBackground(new java.awt.Color(0, 162, 232));
        btn12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12);
        btn12.setBounds(320, 230, 110, 90);

        btn22.setBackground(new java.awt.Color(0, 162, 232));
        btn22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        getContentPane().add(btn22);
        btn22.setBounds(320, 350, 110, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn20.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn20.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn10.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn10.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn01.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn01.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn11.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn11.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
       if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn21.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn21.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn02.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn02.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn12.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn12.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn22.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn22.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        if (turno==true){
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/bolaRoja.png");
            btn00.setIcon(bola);
            turno=false;
        }else {
            ImageIcon bola=new ImageIcon("src/ec/edu/ups/imagenes/xAzul.png");
            btn00.setIcon(bola);
            turno=true;
        }
    }//GEN-LAST:event_btn00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn00;
    private javax.swing.JToggleButton btn01;
    private javax.swing.JToggleButton btn02;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn21;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
